# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

variables:
  GCC_VERSION: 13
  MODULE_NAME: 'slipWall'
  BUILD_IMAGE: "$CI_REGISTRY/containers/chem:4.0-p10-ata-gcc${GCC_VERSION}"
  VERSION: ${CI_COMMIT_TAG}
  SLIPWALL_INSTALL_PACKAGE: "${MODULE_NAME}-${VERSION}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${MODULE_NAME}/${VERSION}"
  TNE_PACKAGENAME: "tne"
  TNE_VERSION: "1.3.6"
  TNE_PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/loci-chem%2F${TNE_PACKAGENAME}/packages/generic/${TNE_PACKAGENAME}/${TNE_VERSION}"
  PLASMA_PACKAGENAME: "plasma"
  PLASMA_VERSION: "1.2.4"
  PLASMA_PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/loci-chem%2F${PLASMA_PACKAGENAME}/packages/generic/${PLASMA_PACKAGENAME}/${PLASMA_VERSION}"
  REACTINGWALL_PACKAGENAME: "reactingWall"
  REACTINGWALL_VERSION: "2.0.4"
  REACTINGWALL_PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/loci-chem%2F${REACTINGWALL_PACKAGENAME}/packages/generic/${REACTINGWALL_PACKAGENAME}/${REACTINGWALL_VERSION}"
  WALLPROBE_PACKAGENAME: "wallProbe"
  WALLPROBE_VERSION: "1.0.3"
  WALLPROBE_PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/loci-chem%2F${WALLPROBE_PACKAGENAME}/packages/generic/${WALLPROBE_PACKAGENAME}/${WALLPROBE_VERSION}"
  GLOBALTIMESTEPPING_PACKAGENAME: "globalTimeStepping"
  GLOBALTIMESTEPPING_VERSION: "1.0.3"
  GLOBALTIMESTEPPING_PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/loci-chem%2F${GLOBALTIMESTEPPING_PACKAGENAME}/packages/generic/${GLOBALTIMESTEPPING_PACKAGENAME}/${GLOBALTIMESTEPPING_VERSION}"
  MAX_PROCS: "4"

default:
  tags:
  - linux

stages:          # List of stages for jobs, and their order of execution
  - build
  - quality_check
  - download
  - test
  - upload
  - release

build_module_openmpi:
  stage: build
  image: "${BUILD_IMAGE}-openmpi"  
  script:
    - whoami
    - pwd
    - ls -lh
    - env
    - git config --global --add safe.directory `pwd`
    - scl enable gcc-toolset-${GCC_VERSION} 'bash ci/build_module ${MAX_PROCS}'
  # Use artifacts to return logs and other files to GitLab (if necessary)
  artifacts:
    paths:
      - slipWall_m.so
      - version.hpp

build_module_mpich:
  stage: build
  image: "${BUILD_IMAGE}-mpich"  
  script:
    - whoami
    - pwd
    - ls -lh
    - env
    - git config --global --add safe.directory `pwd`
    - scl enable gcc-toolset-${GCCVERSION} 'bash ci/build_module ${MAX_CPUS}'
    - mv slipWall_m.so slipWall_mpich_m.so
  # Use artifacts to return logs and other files to GitLab (if necessary)
  artifacts:
    paths:
      - slipWall_mpich_m.so
      - version.hpp

download_modules:
  stage: get_test_dependencies
  image: "${BUILD_IMAGE}-openmpi"  
  script:
    - echo ${GLOBALTIMESTEPPING_PACKAGE_REGISTRY_URL} ${GLOBALTIMESTEPPING_PACKAGENAME}
    - echo ${WALLPROBE_PACKAGE_REGISTRY_URL} ${WALLPROBE_PACKAGENAME}
    - echo ${TNE_PACKAGE_REGISTRY_URL} ${TNE_PACKAGENAME}
    - echo ${PLASMA_PACKAGE_REGISTRY_URL} ${PLASMA_PACKAGENAME}
    - echo ${REACTINGWALL_PACKAGE_REGISTRY_URL} ${REACTINGWALL_PACKAGENAME} ${REACTINGWALL_VERSION}
    - GLOBALTIMESTEPPING_TARBALL=${GLOBALTIMESTEPPING_PACKAGENAME}-${GLOBALTIMESTEPPING_VERSION}-build-openmpi.tar.gz    
    - WALLPROBE_TARBALL=${WALLPROBE_PACKAGENAME}-${WALLPROBE_VERSION}-build-openmpi.tar.gz
    - TNE_TARBALL=${TNE_PACKAGENAME}-${TNE_VERSION}-build-openmpi.tar.gz
    - PLASMA_TARBALL=${PLASMA_PACKAGENAME}-${PLASMA_VERSION}-build-openmpi.tar.gz
    - REACTINGWALL_TARBALL=${REACTINGWALL_PACKAGENAME}-${REACTINGWALL_VERSION}-build-openmpi.tar.gz
    - mkdir modules
    - cd modules
    - 'wget --header="JOB-TOKEN: $CI_JOB_TOKEN" ${GLOBALTIMESTEPPING_PACKAGE_REGISTRY_URL}/${GLOBALTIMESTEPPING_TARBALL}'
    - tar zxvf ${GLOBALTIMESTEPPING_TARBALL}
    - mv ${GLOBALTIMESTEPPING_PACKAGENAME}/*.so .
    - 'wget --header="JOB-TOKEN: $CI_JOB_TOKEN" ${WALLPROBE_PACKAGE_REGISTRY_URL}/${WALLPROBE_TARBALL}'
    - tar zxvf ${WALLPROBE_TARBALL}
    - mv ${WALLPROBE_PACKAGENAME}/*.so .
    - 'wget --header="JOB-TOKEN: $CI_JOB_TOKEN" ${TNE_PACKAGE_REGISTRY_URL}/${TNE_TARBALL}'
    - tar zxvf ${TNE_TARBALL}
    - mv ${TNE_PACKAGENAME}/lib/*.so .
    - 'wget --header="JOB-TOKEN: $CI_JOB_TOKEN" ${PLASMA_PACKAGE_REGISTRY_URL}/${PLASMA_TARBALL}'
    - tar zxvf ${PLASMA_TARBALL}
    - mv ${PLASMA_PACKAGENAME}/lib/*.so .
    - mv ${PLASMA_PACKAGENAME}/collisionIntegrals .
    - 'wget --header="JOB-TOKEN: $CI_JOB_TOKEN" ${REACTINGWALL_PACKAGE_REGISTRY_URL}/${REACTINGWALL_TARBALL}'
    - tar zxvf ${REACTINGWALL_TARBALL}
    - mv ${REACTINGWALL_PACKAGENAME}/*.so .
    - ls -lh
  artifacts:
    paths:
      - modules/globalTimeStepping_m.so
      - modules/wallProbe_m.so
      - modules/tne_m.so
      - modules/plasma_m.so
      - modules/collisionIntegrals
      - modules/reactingWall_m.so

test-regression:
  stage: test
  image: "${BUILD_IMAGE}-openmpi"  
  script:
    - whoami
    - ls -lh
    - env
    - scl enable gcc-toolset-${GCCVERSION} 'bash ci/run_regression_tests ${MAX_PROCS}'


# This will upload a tarball with the CHAR install to the package registry, but only when changes are merged into main
# See: https://docs.gitlab.com/ee/user/project/releases/release_fields.html#release-assets
upload_package_openmpi:
  stage: upload
  image: "${BUILD_IMAGE}-openmpi"  
  rules:
    # only run job if tag created with just a version number
    - if: $CI_COMMIT_TAG =~ /\d+/
  script:
    - |
      MPI_FLAVOR="openmpi"
      mkdir slipWall
      cp slipWall_m.so slipWall/
      tar zcvf ${SLIPWALL_INSTALL_PACKAGE}-build-${MPI_FLAVOR}.tar.gz slipWall
      ls -lh
      echo $PACKAGE_REGISTRY_URL
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${SLIPWALL_INSTALL_PACKAGE}-build-${MPI_FLAVOR}.tar.gz "${PACKAGE_REGISTRY_URL}/${SLIPWALL_INSTALL_PACKAGE}-build-${MPI_FLAVOR}.tar.gz"

upload_package_mpich:
  stage: upload
  image: "${BUILD_IMAGE}-mpich"  
  rules:
    # only run job if tag created with just a version number
    - if: $CI_COMMIT_TAG =~ /\d+/
  script:
    - |
      MPI_FLAVOR="mpich"
      mkdir slipWall
      cp slipWall_mpich_m.so slipWall/
      tar zcvf ${SLIPWALL_INSTALL_PACKAGE}-build-${MPI_FLAVOR}.tar.gz slipWall
      ls -lh
      echo $PACKAGE_REGISTRY_URL
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${SLIPWALL_INSTALL_PACKAGE}-build-${MPI_FLAVOR}.tar.gz "${PACKAGE_REGISTRY_URL}/${SLIPWALL_INSTALL_PACKAGE}-build-${MPI_FLAVOR}.tar.gz"

upload_distribution:
  stage: upload
  image: "${BUILD_IMAGE}-openmpi"  
  rules:
    # only run this job if a tag is created with just a version number
    - if: $CI_COMMIT_TAG =~ /\d+/
  script:
    - |
      ls -lh
      mkdir ${MODULE_NAME}-${VERSION}
      cp README.md ${MODULE_NAME}-${VERSION}/
      cp Makefile ${MODULE_NAME}-${VERSION}/Makefile
      cp *.loci ${MODULE_NAME}-${VERSION}/
      cp version.hpp ${MODULE_NAME}-${VERSION}/
      cp -r testCases ${MODULE_NAME}-${VERSION}/
      rm ${MODULE_NAME}-${VERSION}/testCases/regressionTests.py
      cd ${MODULE_NAME}-${VERSION}
      sed -i '/GITCHECK/,/versioning)/d' Makefile
      sed -i 's/version.hpp//g' Makefile
      sed -i 's/version//g' Makefile
      cd ..
      tar zcvf ${MODULE_NAME}-${VERSION}.tar.gz ${MODULE_NAME}-${VERSION}
      echo $PACKAGE_REGISTRY_URL
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${MODULE_NAME}-${VERSION}.tar.gz "${PACKAGE_REGISTRY_URL}/${MODULE_NAME}-${VERSION}.tar.gz"      


# This will create a release when main is tagged with a version number
release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /\d+/  # only run this job if a tag is created with just a version number
  script:
    - echo "running release_job for ${VERSION}"
  release:
    tag_name: $CI_COMMIT_TAG
    description: ${CI_COMMIT_REF_NAME}-${CI_JOB_ID}
    ref: $CI_COMMIT_SHA
    assets:
      links:
        - name: ${SLIPWALL_INSTALL_PACKAGE}-build-openmpi.tar.gz
          url: "${PACKAGE_REGISTRY_URL}/${SLIPWALL_INSTALL_PACKAGE}-build-openmpi.tar.gz"
          filepath: "/${SLIPWALL_INSTALL_PACKAGE}-build-openmpi.tar.gz"
          link_type: package
        - name: ${SLIPWALL_INSTALL_PACKAGE}-build-mpich.tar.gz
          url: "${PACKAGE_REGISTRY_URL}/${SLIPWALL_INSTALL_PACKAGE}-build-mpich.tar.gz"
          filepath: "/${SLIPWALL_INSTALL_PACKAGE}-build-mpich.tar.gz"
          link_type: package
        - name: ${MODULE_NAME}-${VERSION}.tar.gz
          url: "${PACKAGE_REGISTRY_URL}/${MODULE_NAME}-${VERSION}.tar.gz"
          filepath: "/${MODULE_NAME}-${VERSION}.tar.gz"
          link_type: package

# Code and security scanning jobs
sast:
  stage: quality_check
  artifacts:
    paths:
      - gl-sast-report.*

include:
  - template: Jobs/SAST.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST.gitlab-ci.yml

